server:
  port: 8080

spring:
  application:
    name: SheShield

  datasource:
    url: jdbc:mysql://localhost:3306/sheshield?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: xxxxx
    password:xxxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:xxxxxx
    password: xxxxxx
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: INFO
